// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { env } from '../back-end/src/env';
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Migrations: Supavisor session (5432). Runtime da app usa DATABASE_URL (6543 + pgbouncer) em src/lib/prisma.ts
    url: env.DIRECT_URL,
    // shadowDatabaseUrl: env.DIRECT_URL,
  },
});
